version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
